framework:
    asset_mapper:
        paths:
            - value: '%kernel.project_dir%/src/AdminDomain/Presentation/Resources/assets'
              namespace: admin
            - value: '%kernel.project_dir%/assets/vendor'
              namespace: vendor
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
