doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src'
                prefix: 'App'
