symfonycasts_tailwind:
    input_css:
        - '%kernel.project_dir%/src/AdminDomain/Presentation/Resources/assets/styles/admin.css'
    config_file: 'tailwind.config.js'
    binary_version: 'v4.1.11'

    # Alternatively, you can specify the path to the binary that you manage yourself
    #binary: 'node_modules/.bin/tailwindcss'
