user_domain:
    resource: '../src/UserDomain/Presentation/Controller/'
    type: attribute
    prefix: /api

admin_domain:
    resource: '../src/AdminDomain/Presentation/Controller/'
    type: attribute
    prefix: /admin

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
