services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\ArticleDomain\Repository\ArticleRepositoryInterface: '@App\\Infrastructure\\Repository\\InMemoryArticleRepository'
    App\UserDomain\Repository\UserRepositoryInterface: '@App\\Infrastructure\\Repository\\InMemoryUserRepository'
    App\SharedKernel\Service\SlugGeneratorInterface: '@App\SharedKernel\Service\SlugGenerator'
    App\SharedKernel\Service\UuidGeneratorInterface: '@App\SharedKernel\Service\UuidGenerator'
    App\SharedKernel\Service\DateTimeProviderInterface: '@App\SharedKernel\Service\DateTimeProvider'
    App\SharedKernel\Service\EventDispatcherInterface: '@App\SharedKernel\Service\EventDispatcher'
