services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\ArticleDomain\Domain\Repository\ArticleRepositoryInterface: '@App\\ArticleDomain\\Infrastructure\\Persistence\\DoctrineArticleRepository'
    App\UserDomain\Domain\Repository\UserRepositoryInterface: '@App\\UserDomain\\Infrastructure\\Persistence\\DoctrineUserRepository'
    App\SharedKernel\Service\SlugGeneratorInterface: '@App\SharedKernel\Service\SlugGenerator'
    App\SharedKernel\Service\UuidGeneratorInterface: '@App\SharedKernel\Service\UuidGenerator'
    App\SharedKernel\Service\DateTimeProviderInterface: '@App\SharedKernel\Service\DateTimeProvider'
    App\SharedKernel\Service\EventDispatcherInterface: '@App\SharedKernel\Service\EventDispatcher'
