# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Domain/'
            - '../src/**/Infrastructure/Persistence/Doctrine/Entity/' # если есть кастомные Doctrine entity
            - '../src/Kernel.php'

    # Явная регистрация репозитория (если вдруг не подхватывается)
    App\UserDomain\Infrastructure\Repository\UserRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']
    App\UserDomain\Infrastructure\Repository\RefreshTokenRepository:
        arguments:
            $registry: '@doctrine'
        tags: [ 'doctrine.repository_service' ]
